### ISSUE TITLE
Investigate:🔍 Multiple sln files

### ISSUE THREAD

**Issue by GustavEikaas** [GustavEikaas/easy-dotnet.nvim#114]
Multiple solution files in a project has been mentioned a couple of times and I need to make an assessment.

- What practical benefit is there from having multiple solution files
- What is the drawbacks of implementing support for multiple solution files
- How does Visual studio/rider handle this situation
- Where are these sln files placed in the file structure (siblings, child, parent etc)

Anyone feel free to chime in here

**Comment by AjayKMehta** [comment]
1. I have seen multiple solution files in the same repo to handle cases where you want to include/exclude different projects, e.g. one solution file for all projects and another excludes test projects. If you want to just load certain projects in VS, a better option is to use [solution filters](https://learn.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2022). Another scenario would be a monorepo with different applications/services, each with their own solution.

2. If you try to run `dotnet build` without specifying solution or project when there are multiple solutions/projects, you will get an error: `MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.` For this extension, letting the user choose project/solution to build is a nicer experience IMHO. Maybe we can consider adding **Build All** functionality, .e.g in PowerShell: `Get-ChildItem -Path <RootDir> -Filter *.sln -File -Recurse | % { dotnet build $_.FullName }`.

3. You usually open a project or solution in VS. There is an option to open a folder which I have rarely used.

4. IMHO best not to make assumptions regarding solution file location.

**Comment by AjayKMehta** [comment]
I was merely stating what I have seen in professional settings regarding multiple solutions :smile: 

Being allowed to use Neovim at work would be tough challenge 🙁 

I don't work on C# code outside work much and would probably not need multiple solutions. IMHO it is a niche use case. 

My thoughts are:

Keep status quo: only support single solution (put disclaimer regarding this in **README.md**).

OR

Add a solution picker. If you do so, would be nice to also include an option to build all solutions.

**Comment by GustavEikaas** [comment]
Why would being allowed to use Neoivm at work be a challenge? Due to security concerns?

**Comment by AjayKMehta** [comment]
Yes

**Comment by AjayKMehta** [comment]
Yes, mostly security reasons.

**Comment by GustavEikaas** [comment]
Okay great!

Ill prioritize getting this done as one of my next features

Any input on how to do it?

1. Scan for solution files in current directory and traverse down ~5 depths 
2. If multiple solution files are found spawn a telescope picker
3. Persist the solution file the user chose and default to using this for any operation going forward
4. Add a command `Dotnet solution select`? or something similar to spawn the prompt and pick a different solution

**Comment by GustavEikaas** [comment]
Draft implementation in #185, feel free to test and give feedback
