### ISSUE TITLE
feature: add a public method for checking if file is in dotnet repo

### ISSUE THREAD

**Issue by franroa** [GustavEikaas/easy-dotnet.nvim#70]
**context**:
I would like to call keymaps conditionally depending on the language I am working with. My current solution is to work with filetype, but the problem with that is that I cannot run commands when I am on a file which I havent defined (some files will appear on many repos of different languages, like gitconfig, .env, etc...)

The solution would be to define the keymaps not going by filetype by by condition.
**Also, instead of having this**:
```
      {
        ft = "cs",
        "<leader>oB",
        function()
          require("easy-dotnet").build_solution()
        end,
        desc = "Build .NET App",
      },
```
**It would be nice to have a function like `require("easy-dotnet").is_dotnet_project()`:**

```
      {
        cond=require("easy-dotnet").is_dotnet_project(),
        "<leader>oB",
        function()
          require("easy-dotnet").build_solution()
        end,
        desc = "Build .NET App",
      },
```

Then, the function `require("easy-dotnet").is_dotnet_project()` will recognize if the current file, independent of the filetype, is part of a dotnet project

**Comment by GustavEikaas** [comment]
Making the is_dotnet_project() function is rather easy but it might not work as you expect. It wont check the current file, it will rather check cwd and subfolders for sln and csproject definitions. This is how basically all of the logic inside the plugin works. Are there cases where checking relative to the file instead of vim cwd is necessary? I would love to hear your thoughts. My biggest reason for using cwd is that its simpler and for the way I use it, it will always work as expected.

**Comment by franroa** [comment]
Hi, awesome how fast you develop!
Yes, I didn't express myself correctly. The idea was exactly that: not need to check the current file but the whole path. I have some other places in mind where I will be adding this check. Let me add this function and check if checking the cwd is a problem.
(e.g. I am using git-worktree from primeagen and I will copy my own appsettings from one worktree to another which will not push)
